project_id = "coagqeqodswmjeehvyod"

[functions.generate-prematch-analysis]
verify_jwt = false

[functions.fetch-matches]
verify_jwt = false

[functions.fetch-match-details]
verify_jwt = false

[functions.generate-fan-data]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.generate-team-of-week]
verify_jwt = false

[functions.predict-match]
verify_jwt = false